In [1]:
import numpy as np
from keras import Sequential
from keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [2]:

data = pd.read_csv('all_textures.csv')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [3]:
label_encoder = LabelEncoder()
y_int = label_encoder.fit_transform(y)
onehot_encoder = OneHotEncoder(sparse=False)
y_onehot = onehot_encoder.fit_transform(y_int.reshape(-1, 1))
X_train, X_test, y_train, y_test = train_test_split(X, y_onehot, test_size=0.3)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [4]:
model = Sequential()
model.add(Dense(10, activation='sigmoid', input_dim=72))
model.add(Dense(4, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=100, batch_size=10, shuffle=True)


Epoch 1/100
5/5 [==============================] - 1s 5ms/step - loss: 1.4663 - accuracy: 0.2727
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 1.3650 - accuracy: 0.4773
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 1.4544 - accuracy: 0.2500
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 1.4133 - accuracy: 0.2500
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 1.4167 - accuracy: 0.2500
Epoch 6/100
5/5 [==============================] - 0s 5ms/step - loss: 1.4113 - accuracy: 0.2500
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 1.4072 - accuracy: 0.2500
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 1.4039 - accuracy: 0.2500
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 1.4002 - accuracy: 0.2500
Epoch 10/100
5/5 [==============================] - 0s 4ms/step - loss: 1.3985 - accuracy: 0.2500
Epoch 11/100
5/5 [===========

In [5]:
y_pred = model.predict(X_test)
y_test_int = np.argmax(y_test, axis=1)
y_pred_int = np.argmax(y_pred, axis=1)

# Obliczenie macierzy pomyłek
confusion_mat = confusion_matrix(y_test_int, y_pred_int)
print("Confusion Matrix:")
print(confusion_mat)

1/1 [==============================] - 0s 80ms/step
Confusion Matrix:
[[5 0 0 0]
 [6 0 0 0]
 [0 0 4 0]
 [5 0 0 0]]
